server:
  port: 9122

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/shoppe}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  flyway:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/shoppe}
    locations: classpath:db/migration
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
  lifetime: 30m
  password:
    encoder:
      secret: FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g
      iteration: 64
      key-length: 256

cors:
  allowed-origin: http://localhost:3000

app:
  image:
    bucket: ${APP_IMAGE_BUCKET_PATH:D:\MyProjects\shoppe\images}
    api:
      url: http://localhost:9122/api/v1/images/